#include "Common.ush"
#include "Cloud.ush"

// Ray Marching Parameters
static const uint MAX_DIRECT_STEPS = 256;
static const uint MAX_INDIRECT_STEPS = 256;

// Cloud Parameters
ConstantBuffer<CloudInstance> Cloud;

// Scene Textures
Texture2D<float3> SceneColor;
Texture2D<float> SceneDepth;

// Density Cache Texture
Texture3D<float2> DensityCacheDataSRV;

// Output Texture
RWTexture2D<float4> Output;

#if DEBUG
static int STEP_COUNT = 0;
#endif

/// Anisotropic scattering function for clouds.
/// Source: <https://www.guerrilla-games.com/read/nubis-cubed>
float HenyeyGreenstein(float VdotL, float G) {
    const float G2 = G * G;
    const float num = 1.0 - G2;
    const float denom = 1.0 + G2 - 2.0 * G * VdotL;
    const float rsqrt_denom = rsqrt(denom);
    return num * rsqrt_denom * rsqrt_denom * rsqrt_denom * 0.07957747154594766788444188168626;
}

/// Trace the scene, find out how much density lies along a given path.
float TracePathDensity(const float3 WOrigin, const float3 WDir) {
    // Find the distance at which we exit the bounds of the cloud volume.
    const float WExitDistance = RayAABB(WOrigin, WDir, Cloud.Position - HALF_VOLUME_SIZE, Cloud.Position + HALF_VOLUME_SIZE).y;
    
    // Traversal state.
    float WDistance = 0.0, WPathDensity = 0.0;
    
    for (uint s = 0; s < 256; ++s) {
        // Check if we've exited the cloud volume.
        if (WDistance >= WExitDistance) break;
        
        // Calculate the location of the current step, in world and local space.
        const float3 WSampleLocation = WOrigin + WDir * WDistance;
        const float3 LSampleLocation = WorldToCloudSpace(Cloud, WSampleLocation);
        
        // Sample the cloud volume signed distance field.
        const float WCloudDistance = SampleCloudDistance(Cloud, LSampleLocation);
        const float WStepSize = max(Cloud.SecondaryStep, WCloudDistance);
        
        // Check if the current step is *inside* the cloud volume.
        if (WCloudDistance < 0.0) {
            const float DimensionalProfile = DistanceToDimensionalProfile(Cloud, WCloudDistance);
            WPathDensity += SampleCloudDensity(Cloud, DimensionalProfile, LSampleLocation) * WStepSize;
            if (WPathDensity > Cloud.SecondaryExtinctThreshold) return 32.0;
        }
        
        // Take the next step.
        WDistance += WStepSize;
    }
    
    return WPathDensity;
}

void IntegrateCloudSample(
    inout float3 OutLuminance, inout float OutAbsorption, 
    const float3 LSampleLocation, const float3 WSampleLocation,
    const float WStepSize, const float WCloudDistance,
    const float3 SunAnisotropy, const float SunDot
) {
    // Sample and uprezz the cloud density at the sample location.
    const float DimensionalProfile = DistanceToDimensionalProfile(Cloud, WCloudDistance);
    const float Density = SampleUprezzedCloudDensity(Cloud, DimensionalProfile, LSampleLocation, WSampleLocation);
    const float StepDensity = WStepSize * Density;
    
    // Update the path absorption based on the density at the current path segment.
    OutAbsorption = saturate(OutAbsorption + StepDensity * (1.0 - OutAbsorption));
    
    // Read path density information about the current location from the pre-computed cache.
    const float2 CachedDensity = DensityCacheDataSRV.Sample(GlobalBilinearClampedSampler, LSampleLocation);
    
    // Calculate how much light from the sun reaches the sample location.
    const float SunPathDensity = Remap(CachedDensity.x, 0.0, 1.0, 0.0, 32.0);
    const float3 SunAbsorption = -Cloud.Absorption * SunPathDensity;
    const float StepScattering = StepDensity * (1.0 - OutAbsorption);
    const float3 SunScattering = SunAnisotropy * StepScattering;
    
    // Integrate direct out-scattering from the sun.
    if (Cloud.DirectScattering) {
        OutLuminance += SunScattering * exp(SunAbsorption);
    }
    
    // Integrate multi-scattering approximation from the sun.
    if (Cloud.MultiScattering) {
        const float InnerGlow = Remap(WCloudDistance, -128.0, 0.0, 0.05, 0.25);
        const float AnisotropicScattering = Remap(SunDot, 0.0, 0.9, 0.25, InnerGlow);
        const float MultiScattering = DimensionalProfile * exp(-SunPathDensity * AnisotropicScattering);
        // OutLuminance += Cloud.SunLuminance * StepScattering * DimensionalProfile * exp(SunAbsorption * AnisotropicScattering);
        OutLuminance += Cloud.SunLuminance * StepScattering * MultiScattering; // * exp(-SunPathDensity);
    }
    
    // Integrate ambient out-scattering from the environment.
    if (Cloud.AmbientScattering) {
        //const float AmbientDensity = Remap(CachedDensity.y, 0.0, 1.0, 0.0, 32.0);
        //const float3 AmbientTransmittance = exp(-Cloud.Absorption * AmbientDensity);
        OutLuminance += StepScattering * pow(1.0 - DimensionalProfile, 0.5) * Cloud.AmbientLuminance; // * AmbientTransmittance;
    }
}

float3 TraceVolume(const float3 ViewColor, const float3 WOrigin, const float3 WDir) {
    // Find the distance at which we enter & exit the bounds of the cloud volume.
    const float2 WEntryExitDistance = RayAABB(WOrigin, WDir, Cloud.Position - HALF_VOLUME_SIZE, Cloud.Position + HALF_VOLUME_SIZE);
    if (WEntryExitDistance.x > WEntryExitDistance.y) return ViewColor;
    
    // Traversal state.
    float WDistance = WEntryExitDistance.x;
    float3 Luminance = 0.0;
    float Absorption = 0.0;
    
    // Sun out-scattering will be identical everywhere along the ray, pre-calculate it.
    const float SunDot = dot(WDir, Cloud.SunDir);
    const float3 SunAnisotropy = Cloud.SunLuminance * HenyeyGreenstein(SunDot, 0.2);
    
    // Integrate luminance along the ray.
    for (uint s = 0; s < MAX_DIRECT_STEPS; ++s) {
        // Check if we've exited the cloud volume.
        if (WDistance >= WEntryExitDistance.y) break;
        
        // Calculate the location of the current step, in world and local space.
        const float3 WSampleLocation = WOrigin + WDir * WDistance;
        const float3 LSampleLocation = WorldToCloudSpace(Cloud, WSampleLocation);
        
        // Calculate an adaptive step size depending on distance from the camera.
        const float WAdaptiveStepSize = max(Cloud.PrimaryNearStep, sqrt(WDistance) * Cloud.PrimaryStepPerDistance);
        
        // Sample the cloud volume signed distance field.
        const float WCloudDistance = SampleCloudDistance(Cloud, LSampleLocation);
        const float WStepSize = max(WCloudDistance, WAdaptiveStepSize);
        
        // Check if the current step is *inside* the cloud volume.
        if (WCloudDistance < 0.0) {
            IntegrateCloudSample(
                Luminance,  // Out
                Absorption, // Out
                LSampleLocation, WSampleLocation,
                WStepSize, WCloudDistance, 
                SunAnisotropy, SunDot
            );
        }
        
        // Take the next step.
        WDistance += WStepSize;
    }
    
    // Finally, combine the view color with the luminance based on the absorption.
    return ViewColor * (1.0 - Absorption) + Luminance;
}

// Compute Shader code
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint2 DispatchThreadId : SV_DispatchThreadID) {
    // Calculate the pixel coordinate of this thread.
    const uint2 Pixel = View.ViewRectMinAndSize.xy + DispatchThreadId;
    
	// Make sure this pixel isn't outside the viewport bounds.
    if (any(Pixel >= View.ViewRectMinAndSize.zw)) return;
	
    // Calculate the UV coordinate of the current pixel.
    const float2 UV = GetPixelUV(Pixel);
    
    // Get the ray origin (in Meters) & direction.
    const float3 RayOrigin = GetRayOrigin() * CM_TO_M;
    const float3 RayDirection = GetRayDirection(UV);
    
    // Ray vs Sphere intersection test.
    const float3 FinalColor = TraceVolume(SceneColor[Pixel], RayOrigin, RayDirection);
    
#if DEBUG
    Output[Pixel] = float4((float)STEP_COUNT / (float)MAX_DIRECT_STEPS, 0.0, 0.0, 1.0);
#else
    Output[Pixel] = float4(FinalColor, 1.0);
#endif
}
