#pragma once

#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"
#include "Common.ush"

// Volume constants.
static const float METERS_PER_VOXEL = 8.0; // 8 m
static const float VOXELS_PER_METER = 1.0 / METERS_PER_VOXEL;
static const float3 VOLUME_RESOLUTION = float3(512, 512, 64);
static const float3 VOLUME_SIZE = METERS_PER_VOXEL * VOLUME_RESOLUTION;
static const float3 HALF_VOLUME_SIZE = VOLUME_SIZE * 0.5;
static const float3 RCP_VOLUME_SIZE = 1.0 / VOLUME_SIZE;
static const float3 RCP_HALF_VOLUME_SIZE = 1.0 / HALF_VOLUME_SIZE;

/// 4 types of noise packed into a single texture.
/// Channels: HFAlligator, HFCurlyWorley, LFAlligator, LFCurlyWorley
Texture3D<float4> Noise;

/// Collection of data required to render a cloud.
/// All length/distance values are expressed in Meters.
struct CloudInstance {
    // Volume Data
    float3 Position;
    float3 Absorption;
    float Density;
    float ProfileWidth;
    
    // Light Data
    float3 SunDir;
    float3 SunLuminance;
    float3 AmbientLuminance;
        
    // Primary Ray Options
    float PrimaryNearStep;
    float PrimaryStepPerDistance;
    float PrimaryMinSDFStep;
    
    uint DirectScattering;
    uint MultiScattering;
    uint AmbientScattering;
    
    // Secondary Ray Options
    float SecondaryStep;
    float SecondaryExtinctThreshold;
    
    float NoiseFreq;
    float3 WindSpeed;
    
    // Textures
    Texture3D<float> DensityTexture;
    Texture3D<float> SDFTexture;
};

float ValueErosion(const float Value, const float Erosion) {
	const float InvErosion = (1.0 - Erosion);
    return saturate((Value - Erosion) / InvErosion);
}

/// Transform a position from world-space to cloud texture-space.
/// NOTE: `Point` is expected to be in Meters. (not the usual Centimeters which UE uses as units)
float3 WorldToCloudSpace(ConstantBuffer<CloudInstance> Cloud, const float3 Point) {
    return (Point - Cloud.Position) * RCP_HALF_VOLUME_SIZE * 0.5 + 0.5;
}

/// Sample the cloud SDF.
float SampleCloudDistance(ConstantBuffer<CloudInstance> Cloud, const float3 LSampleLocation) {
    // The SDF is stored from -32 to 512 in a UNorm texture encoded in voxel-space.
    const float NormDistance = Cloud.SDFTexture.Sample(GlobalBilinearClampedSampler, LSampleLocation);
    return (NormDistance * (32.0 + 512.0) - 32.0) * METERS_PER_VOXEL;
}

/// Convert the SDF of a cloud to a dimensional profile.
float DistanceToDimensionalProfile(ConstantBuffer<CloudInstance> Cloud, const float Distance) {
    return saturate(-Distance / Cloud.ProfileWidth);
}

/// Sample the cloud density.
float SampleCloudDensity(ConstantBuffer<CloudInstance> Cloud, const float DimensionalProfile, const float3 LSampleLocation) {
    // Sample the density scale texture.
    const float DensityScale = Cloud.DensityTexture.Sample(GlobalBilinearClampedSampler, LSampleLocation);
    
    // Remap the density scale and apply it to the dimensional profile.
    const float PowDensity = pow(saturate(DensityScale * Cloud.Density), 4.0);
    const float ScaledDensity = DimensionalProfile * PowDensity;
    return pow(ScaledDensity, lerp(0.3, 0.6, max(0.00001, PowDensity)));
}

/// Sample the cloud density with noise applied to appear higher resolution.
float SampleUprezzedCloudDensity(ConstantBuffer<CloudInstance> Cloud, const float DimensionalProfile, const float3 LSampleLocation, const float3 WSampleLocation) {
    // Sample the density scale texture.
    const float DensityScale = Cloud.DensityTexture.Sample(GlobalBilinearClampedSampler, LSampleLocation);
    
    // Noise texture sampling.
    const float3 SweptUVW = WSampleLocation - Cloud.WindSpeed * View.GameTime;
    const float3 NoiseUVW = SweptUVW * Cloud.NoiseFreq;
    const float4 NoiseSample = Noise.Sample(GlobalBilinearWrappedSampler, NoiseUVW);
    
    // Wispy noise. (used in areas of decreasing pressure)
    const float WispyNoise = lerp(NoiseSample.a, NoiseSample.g, DimensionalProfile);
    
    // Billowy noise. (used in areas of increasing pressure)
    const float BillowyFreqGradient = pow(DimensionalProfile, 0.25);
    const float BillowyNoise = lerp(NoiseSample.b * 0.3, NoiseSample.r * 0.3, BillowyFreqGradient);

    // Composite the two kinds of noise and apply it to the dimensional profile.
    const float NoiseComposite = lerp(WispyNoise, BillowyNoise, 1.0); // TODO: Interpolate noises.
    const float ErodedProfile = ValueErosion(DimensionalProfile, NoiseComposite);
    
    // Finally, apply the user defined density scale.
    const float PowDensity = pow(saturate(DensityScale * Cloud.Density), 4.0);
    const float ScaledDensity = ErodedProfile * PowDensity;
    return pow(ScaledDensity, lerp(0.3, 0.6, max(0.00001, PowDensity)));
}
