#include "Common.ush"
#include "Cloud.ush"

static const uint MAX_STEPS = 128;
static const uint MAX_AMBIENT_STEPS = 64;
static const float MAX_PATH_DENSITY = 32.0;

// Cloud Parameters
ConstantBuffer<CloudInstance> Cloud;
RWTexture3D<float2> DensityCacheData;

/// Trace the scene, find out how much density lies along a given path.
float TracePathDensity(const float3 WOrigin, const float3 WDir) {
    // Find the distance at which we exit the bounds of the cloud volume.
    const float WExitDistance = RayAABB(WOrigin, WDir, Cloud.Position - HALF_VOLUME_SIZE, Cloud.Position + HALF_VOLUME_SIZE).y;
    
    // Traversal state.
    float WDistance = 0.0, WPathDensity = 0.0;
    
    for (uint s = 0; s < MAX_STEPS; ++s) {
        // Check if we've exited the cloud volume.
        if (WDistance >= WExitDistance) break;
        
        // Calculate the location of the current step, in world and local space.
        const float3 WSampleLocation = WOrigin + WDir * WDistance;
        const float3 LSampleLocation = WorldToCloudSpace(Cloud, WSampleLocation);
        
        // Sample the cloud volume signed distance field.
        const float WCloudDistance = SampleCloudDistance(Cloud, LSampleLocation);
        const float WStepSize = max(Cloud.SecondaryStep, WCloudDistance);
        
        // Check if the current step is *inside* the cloud volume.
        if (WCloudDistance < 0.0) {
            const float DimensionalProfile = DistanceToDimensionalProfile(Cloud, WCloudDistance);
            WPathDensity += SampleCloudDensity(Cloud, DimensionalProfile, LSampleLocation) * WStepSize;
            if (WPathDensity > Cloud.SecondaryExtinctThreshold) return MAX_PATH_DENSITY;
        }
        
        // Take the next step.
        WDistance += WStepSize;
    }
    
    return WPathDensity;
}

/// Trace the scene, find out aproximately how much occlusion there is within a cone.
float TraceAmbientCone(const float3 WOrigin, const float3 WDir) {
    // Intersect the bounds of the volume.
    const float WExitDistance = RayAABB(WOrigin, WDir, Cloud.Position - HALF_VOLUME_SIZE, Cloud.Position + HALF_VOLUME_SIZE).y;
    
    // Traversal variables.
    const float HalfAngle = 0.6; // ~35 deg
    const float TanHalfAngle = tan(HalfAngle);
    float WDistance = 24.0; // m
    float WOcclusion = 0.0;
    
    for (uint s = 0; s < MAX_AMBIENT_STEPS; ++s) {
        if (WDistance >= WExitDistance) break;
        const float WConeRadius = TanHalfAngle * WDistance;
        const float WConeDiameter = WConeRadius * 2.0;
        
        // Calculate the location of the current step, in world and local space.
        const float3 WSampleLocation = WOrigin + WDir * WDistance;
        const float3 LSampleLocation = WorldToCloudSpace(Cloud, WSampleLocation);
        
        // Sample the cloud volume signed distance field.
        const float WCloudDistance = max(0.0, SampleCloudDistance(Cloud, LSampleLocation));
        
        // Some of the cloud is inside the cone at the current step.
        if (WCloudDistance < WConeRadius) {
            const float Coverage = (WConeRadius - WCloudDistance) / WConeRadius;
            WOcclusion += (1.0 - WOcclusion) * (Coverage * 0.5);
        }
        WDistance += WConeDiameter;
    }
    
    return WOcclusion;
}

// Compute Shader code
[numthreads(THREADS_X, THREADS_Y, THREADS_Z)]
void MainCS(uint3 DispatchThreadId : SV_DispatchThreadID) {
    // Calculate the cache slot origin for this thread.
    const uint FrameIndex = View.FrameCounter;
    const uint3 OutputId = (DispatchThreadId << 1u) + uint3(FrameIndex & 1u, (FrameIndex >> 1u) & 1u, (FrameIndex >> 2u) & 1u);
    const float3 Voxel = float3(OutputId) * 2.0 + 1.0;
    const float3 WOrigin = (Cloud.Position - HALF_VOLUME_SIZE) + Voxel * METERS_PER_VOXEL;
    
    // Check if there's cloud at the origin, if not, exit early.
    const float WCloudDistance = SampleCloudDistance(Cloud, WorldToCloudSpace(Cloud, WOrigin));
    if (WCloudDistance > 0.0) return;
    
    // Trace the path density toward the sun for this cache slot.
    const float WPathDensity = TracePathDensity(WOrigin, Cloud.SunDir);
    
    float AmbientOcclusion = 0.0;
    AmbientOcclusion += TraceAmbientCone(WOrigin, float3( 1.0,  0.0,  0.0)) * 0.125;
    AmbientOcclusion += TraceAmbientCone(WOrigin, float3(-1.0,  0.0,  0.0)) * 0.125;
    AmbientOcclusion += TraceAmbientCone(WOrigin, float3( 0.0,  1.0,  0.0)) * 0.125;
    AmbientOcclusion += TraceAmbientCone(WOrigin, float3( 0.0, -1.0,  0.0)) * 0.125;
    AmbientOcclusion += TraceAmbientCone(WOrigin, float3( 0.0,  0.0,  1.0)) * 0.500;
    
    // const float AmbientDensity = TracePathDensity(WOrigin, float3(0.0, 0.0, 1.0));
    
    // Store the path density data into the cache slot.
    DensityCacheData[OutputId] = float2(
        Remap(WPathDensity, 0.0, MAX_PATH_DENSITY, 0.0, 1.0),
        saturate(AmbientOcclusion)
    );
}
